/** Portuguese presentation for the rehearsal console's Traditional Chinese source copy. */

type LocaleProbe = (key: 'localeCode') => string

const PORTUGUESE_TEXT: Readonly<Record<string, string>> = {
  '工作台': 'Painel',
  '智能體與渠道': 'Agentes e canais',
  '對話編排': 'Fluxos de conversa',
  '知識與回答': 'Conhecimento e respostas',
  '模型與發音': 'Modelos e pronúncia',
  '會話中心': 'Conversas',
  '質檢與評測': 'Qualidade e avaliação',
  '報表與大屏': 'Relatórios e ecrã geral',
  '當前知識庫': 'Base de conhecimento atual',
  '發音與詞庫': 'Pronúncia e léxico',
  '集中處理服務反饋、知識更新與質量覆核。': 'Centralize o retorno do serviço, as atualizações de conhecimento e a revisão da qualidade.',
  '管理服務入口、智能體策略與接待體驗。': 'Gira os canais de atendimento, as estratégias dos agentes e a experiência do cliente.',
  '編排服務路徑，驗證正常與異常分支。': 'Configure percursos de serviço e valide os cenários normais e de exceção.',
  '從文檔加工到回答策略，管理每一份服務依據。': 'Gira todas as fontes do serviço, desde o tratamento de documentos até às estratégias de resposta.',
  '維護模型能力、澳門地址與粵語讀音規則。': 'Gira os modelos, os endereços de Macau e as regras de pronúncia em cantonês.',
  '維護通用發音規則、詞條糾偏與澳門地址對照。': 'Gira regras gerais de pronúncia, correções de termos e referências de endereços de Macau.',
  '客服回答': 'Resposta do atendimento',
  '發音管理分類': 'Categorias de pronúncia',
  '查閲服務記錄，定位問題與處理依據。': 'Consulte os registos de atendimento e identifique problemas e respetivas evidências.',
  '跟蹤問題整改，驗證當前版本並完成覆核。': 'Acompanhe as correções, valide a versão atual e conclua a revisão.',
  '按渠道和回答策略分析服務分佈。': 'Analise a distribuição do serviço por canal e estratégia de resposta.',
  '深繹未來 · 澳門電力': 'Deep Future · CEM Macau',
  '退出大屏': 'Sair do ecrã inteiro',
  '全屏展示': 'Ver em ecrã inteiro',
  '返回客服': 'Voltar ao atendimento',
  '工作區設定': 'Definições da área de trabalho',
  '配置與數據説明': 'Configuração e dados',
  '工作區內置驗證用例，配置保存在當前頁籤；刷新後重置。運行數據從已接入服務讀取。': 'A área de trabalho inclui casos de validação. As alterações permanecem neste separador e são repostas ao atualizar. Os dados de execução são lidos dos serviços ligados.',
  '渠道與詞典尚未接入發佈，草稿修改不會影響運行中的客服。': 'Os canais e dicionários ainda não estão ligados à publicação. As alterações ao rascunho não afetam o serviço em execução.',
  '重置工作區': 'Repor área de trabalho',
  '清除當前頁籤的工作區草稿和驗證進度？運行配置、歷史會話和知識庫不會被刪除。': 'Limpar os rascunhos e o progresso de validação deste separador? A configuração em execução, o histórico de conversas e a base de conhecimento não serão eliminados.',
  '確認重置工作區': 'Confirmar reposição',
  '取消': 'Cancelar',
  '關閉操作提示': 'Fechar aviso',
  '數據來源': 'Origem dos dados',
  '營運工作區': 'Área de operações',
  '運行數據': 'Dados de execução',
  '已接入服務': 'Serviço ligado',
  '配置與驗證': 'Configuração e validação',
  '服務質量 · 重點關注': 'Qualidade do serviço · Em destaque',
  '從每次對話，發現服務改進機會': 'Encontre oportunidades de melhoria em cada conversa',
  '檢查歷史會話，查看六維評分與原始執行證據，跟蹤人工覆核和整改驗收。': 'Consulte conversas anteriores, pontuações em seis dimensões e evidências de execução, e acompanhe a revisão humana e a validação das correções.',
  '進入會話質檢 →': 'Abrir controlo de qualidade →',
  '服務營運': 'Operações do serviço',
  '持續改進': 'Melhoria contínua',
  '營運任務': 'Tarefas operacionais',
  '質量檢查與覆核': 'Controlo e revisão da qualidade',
  '查看質檢任務、待覆核結果和未完成整改': 'Consulte avaliações, resultados por rever e correções por concluir.',
  '計劃停電通知入庫': 'Importar aviso de interrupção programada',
  '審核完成 · 待發布': 'Revisão concluída · A aguardar publicação',
  '待完成文檔加工與審核': 'Tratamento e revisão do documento pendentes',
  '查看': 'Ver',
  '快捷入口': 'Acessos rápidos',
  '驗證集會話': 'Conversas do conjunto de validação',
  '電話 / Web / App': 'Telefone / Web / App',
  '已完成': 'Concluídas',
  '按工作區處理狀態統計': 'Calculado pelo estado na área de trabalho',
  '待覆核': 'A rever',
  '需要營運人員跟進': 'Requer acompanhamento operacional',
  '規則迴歸': 'Regressão das regras',
  '待運行': 'Por executar',
  '獨立測試集': 'Conjunto de testes independente',
  '全部渠道': 'Todos os canais',
  '電話': 'Telefone',
  '諮詢主題': 'Tema da consulta',
  '回答策略': 'Estratégia de resposta',
  '服務分佈': 'Distribuição do serviço',
  '驗證集': 'Conjunto de validação',
  '當前篩選': 'Filtro atual',
  '條記錄': 'registos',
  '報表渠道': 'Canal do relatório',
  '類回答': 'Resposta da classe',
  '統計口徑': 'Critérios estatísticos',
  '當前圖表來自內置驗證集，不作為線上業務指標。迴歸結果單獨統計，運行數據請在工作台切換查看。': 'Os gráficos usam o conjunto de validação integrado e não representam indicadores de produção. Os resultados de regressão são contabilizados separadamente; alterne para os dados de execução para consultar o serviço real.',
  '澳門智能客服': 'Atendimento inteligente de Macau',
  '澳門智能客服 · 知識導航': 'Atendimento inteligente de Macau · Navegação de conhecimento',
  '知識檢索型': 'Pesquisa de conhecimento',
  '知識導航型': 'Navegação de conhecimento',
  '基於已審核資料檢索回答，適用於日常繳費與服務諮詢。': 'Pesquisa conteúdos aprovados para responder a questões de pagamento e atendimento geral.',
  '按知識主題組織資料，適用於結構化服務政策查詢。': 'Organiza conteúdos por tema para consultas estruturadas sobre políticas de serviço.',
  '澳門粵語': 'Cantonês de Macau',
  '繁體中文': 'Chinês tradicional',
  '普通話': 'Mandarim',
  '葡語': 'Português',
  '英語': 'Inglês',
  '智能體配置': 'Configurar agente',
  '渠道接入與服務預覽': 'Canais e pré-visualização do serviço',
  '接入狀態：未接入 · 可先配置服務入口與歡迎語。': 'Estado: não ligado · Pode configurar antecipadamente o canal e a saudação.',
  '渠道名稱': 'Nome do canal',
  '預設語言': 'Idioma predefinido',
  '歡迎語': 'Saudação',
  '啟用服務入口': 'Ativar canal de atendimento',
  '服務路由：歡迎語 → 語言選擇 → 智能服務 → 必要時轉人工。未接入真實號碼。': 'Percurso: saudação → seleção do idioma → atendimento inteligente → operador, quando necessário. Ainda não existe um número real ligado.',
  '入口：服務諮詢 · 賬單查詢 · 停電報修；使用客戶身份。': 'Serviços: informações · consulta de fatura · comunicação de interrupções; utiliza a identidade do cliente.',
  '保存渠道草稿': 'Guardar rascunho do canal',
  '有未保存的修改': 'Existem alterações por guardar',
  '草稿已保存': 'Rascunho guardado',
  '效果預覽': 'Pré-visualização',
  '澳電智能客服': 'Atendimento inteligente da CEM',
  '預覽已啟用': 'Pré-visualização ativa',
  '預覽已停用': 'Pré-visualização desativada',
  '服務入口已停用。': 'O canal de atendimento está desativado.',
  '繳費諮詢': 'Informações de pagamento',
  '本期賬單金額查詢': 'Consulta do valor da fatura atual',
  '用電安全諮詢': 'Consulta sobre segurança elétrica',
  '停電報修': 'Comunicar interrupção',
  '預覽不發起真實通話，也不播放合成語音。': 'A pré-visualização não inicia chamadas reais nem reproduz voz sintetizada.',
  '語音文本規範化': 'Normalização do texto de voz',
  '先按語言和場景處理通用讀法': 'Aplique primeiro as pronúncias gerais por idioma e contexto',
  '會話原文保持不變，只對送入 TTS 的文本副本展開縮寫、數字、日期和金額。': 'O texto original da conversa permanece inalterado. Apenas a cópia enviada ao TTS expande abreviaturas, números, datas e valores.',
  '發音規則生效流程': 'Processo de aplicação das regras de pronúncia',
  '模型回答': 'Resposta do modelo',
  '確定語言': 'Detetar idioma',
  '通用規則': 'Regras gerais',
  '詞條糾偏': 'Correções de termos',
  'TTS 適配': 'Adaptação para TTS',
  '語音輸出': 'Saída de voz',
  '通用發音規則': 'Regras gerais de pronúncia',
  '優先級數字越小越先執行；後續的精確詞條可以覆蓋通用結果。': 'Quanto menor o número, maior a prioridade. Uma correção exata posterior pode substituir o resultado geral.',
  '已啟用': 'Ativadas',
  '語言': 'Idioma',
  '試讀語言': 'Idioma da audição de teste',
  '類型': 'Tipo',
  '發音規則類型': 'Tipo de regra de pronúncia',
  '全部規則': 'Todas as regras',
  '地址': 'Endereço',
  '數字': 'Número',
  '機構': 'Entidade',
  '金額': 'Valor',
  '日期': 'Data',
  '當前語言可用': 'Disponíveis no idioma atual:',
  '條': 'regras',
  '優先級': 'Prioridade',
  '規則': 'Regra',
  '匹配': 'Correspondência',
  '狀態': 'Estado',
  '已停用': 'Desativada',
  '匹配方式': 'Método de correspondência',
  '規則條件': 'Condição',
  '輸出方式': 'Resultado',
  '參考': 'Referência',
  '規則範例': 'Exemplo da regra',
  '啟用此規則': 'Ativar esta regra',
  '變更僅保存在當前工作區，未發佈到電話服務。': 'As alterações ficam apenas nesta área de trabalho e não são publicadas no serviço telefónico.',
  '規則試讀': 'Teste das regras',
  '顯示文本與播報文本分開，便於核對知識庫縮寫和地址。': 'Compare separadamente o texto apresentado e o texto falado para verificar abreviaturas e endereços.',
  '測試文本': 'Texto de teste',
  '發音規則測試文本': 'Texto de teste das regras de pronúncia',
  '運行規則試讀': 'Executar teste das regras',
  '客戶看到的文本': 'Texto apresentado ao cliente',
  '送入 TTS 的文本': 'Texto enviado ao TTS',
  '未命中規則': 'Nenhuma regra aplicada',
  '澳門地址與機構縮寫': 'Abreviaturas de endereços e entidades de Macau',
  '用於通用規則的參考對照，不覆蓋客戶看到的標準名稱。': 'Tabela de referência para regras gerais; não altera os nomes apresentados ao cliente.',
  '參考表已錄入': 'Tabela de referência carregada',
  '地址縮寫': 'Abreviatura do endereço',
  '播報語義': 'Forma falada',
  '銀行縮寫': 'Abreviatura do banco',
  '中文': 'Chinês',
  '英文 / 葡文名稱': 'Nome em inglês / português',
  '對地名和業務詞做完整詞匹配，優先於通用規則，不做全局單字替換。': 'Faz correspondência exata de topónimos e termos do serviço. Tem prioridade sobre as regras gerais e não substitui caracteres isolados globalmente.',
  '搜索地址或詞條': 'Pesquisar endereço ou termo',
  '搜索中文、葡文、讀音…': 'Pesquisar chinês, português ou pronúncia…',
  '詞條分類': 'Categoria do termo',
  '全部詞條': 'Todos os termos',
  '地名': 'Topónimo',
  '業務': 'Serviço',
  '幣種': 'Moeda',
  '待補充': 'Por completar',
  '個詞條': 'termos',
  '清空篩選': 'Limpar filtros',
  '詞條': 'Termo',
  '葡文 / 標識': 'Português / identificador',
  '類別': 'Categoria',
  '粵拼糾偏': 'Correção Jyutping',
  '沒有匹配的詞條。': 'Nenhum termo corresponde à pesquisa.',
  '糾偏詳情': 'Detalhes da correção',
  '場景：澳門地址播報': 'Contexto: leitura de endereços de Macau',
  '語言：澳門粵語': 'Idioma: cantonês de Macau',
  '範圍：完整詞條匹配': 'Âmbito: correspondência exata do termo',
  '粵拼讀音': 'Pronúncia Jyutping',
  '保存詞條糾偏': 'Guardar correção do termo',
  '當前版本已保存': 'Versão atual guardada',
  '結構化讀音預覽 · 非合成試聽': 'Pré-visualização estruturada · sem síntese de voz',
  '原詞：': 'Termo original:',
  '粵拼：': 'Jyutping:',
  '尚未填寫': 'Não preenchido',
  '使用推薦讀音': 'Usar pronúncia recomendada',
  '此層用於通用規則無法解決的專名、地名和多音字。': 'Esta camada trata nomes próprios, topónimos e caracteres com várias pronúncias que as regras gerais não resolvem.',
  '查看會話質檢 →': 'Ver controlo de qualidade →',
  '模型與發音分類': 'Categorias de modelos e pronúncia',
  '模型配置': 'Configuração de modelos',
  '提示詞模板': 'Modelo de instruções',
  '發音規則庫': 'Regras de pronúncia',
  '澳門地址庫': 'Endereços de Macau',
  '對話模型': 'Modelo de conversa',
  '組織自然語言回答': 'Produz respostas em linguagem natural',
  '可配置': 'Configurável',
  '向量模型': 'Modelo de vetorização',
  '將知識轉為可檢索表示': 'Converte conhecimento numa representação pesquisável',
  '由知識庫配置管理': 'Gerido na configuração da base de conhecimento',
  '重排模型': 'Modelo de reordenação',
  '優化候選知識排序': 'Melhora a ordem dos conteúdos candidatos',
  '由檢索配置管理': 'Gerido na configuração da pesquisa',
  '語音識別': 'Reconhecimento de voz',
  '將客戶語音轉為文字': 'Converte a voz do cliente em texto',
  '沿用當前電話服務': 'Utiliza o serviço telefónico atual',
  '語音合成': 'Síntese de voz',
  '將回復轉為自然語音': 'Converte a resposta em voz natural',
  '能力目錄': 'Capacidade',
  '模型與服務配置': 'Configuração de modelos e serviços',
  '此目錄不代表端點健康檢查。工作區草稿不會覆蓋實際模型、密鑰或語音配置。': 'Este catálogo não representa uma verificação do estado dos serviços. Os rascunhos não substituem modelos, chaves ou configurações de voz reais.',
  '管理模型配置': 'Gerir configuração de modelos',
  'C 類知識問答提示詞': 'Instruções para respostas de conhecimento da classe C',
  '工作區模板 · 僅修改後臺預覽，不注入真實客服會話。': 'Modelo da área de trabalho · Altera apenas a pré-visualização e não é usado em conversas reais.',
  '回答要求': 'Requisitos da resposta',
  '約束：僅使用審核知識；證據不足時澄清；後臺顯示依據；電話播報不含文檔編號。': 'Regras: usar apenas conhecimento aprovado; pedir esclarecimentos quando a evidência for insuficiente; mostrar as fontes na consola; não ler números de documentos ao telefone.',
  '保存提示詞草稿': 'Guardar rascunho das instruções',
  '業務查詢超時 → 轉人工分支；坐席線路未接入。': 'A consulta excedeu o tempo limite → encaminhar para um operador; o canal de operadores ainda não está ligado.',
  '沒有匹配記錄 → 澄清信息；不編造業務結果。': 'Sem registos correspondentes → pedir esclarecimentos; não inventar resultados do serviço.',
  '測試賬單：澳門元 328.50，繳費期限 9 月 30 日。': 'Fatura de teste: 328,50 patacas, com pagamento até 30 de setembro.',
  '報修確認：是否需要登記報修？工單接口未接入。': 'Confirmação: pretende registar a avaria? A interface de ordens de serviço ainda não está ligada.',
  '根據工作區知識回答繳費方式；後臺保留來源。': 'Responder sobre métodos de pagamento com base no conhecimento da área de trabalho; as fontes ficam registadas na consola.',
  '試運行完成。': 'Teste concluído.',
  '使用輸入。': 'utiliza os dados de entrada.',
  '選擇場景，開始試運行。': 'Selecione um cenário para iniciar o teste.',
  '工作區草稿': 'Rascunho da área de trabalho',
  '節點': 'nós',
  '拖動節點調整佈局；在右側選擇下一節點連線。支持鍵盤方向鍵移動節點。': 'Arraste os nós para ajustar a disposição e selecione o nó seguinte à direita. Também pode mover os nós com as teclas de direção.',
  '檢查流程': 'Verificar fluxo',
  '基礎校驗通過：節點可達、名稱完整、出口有效、無循環。': 'Validação concluída: os nós são alcançáveis, têm nomes e saídas válidas e não existem ciclos.',
  '服務流程畫布': 'Diagrama do fluxo de serviço',
  '正常出口可編輯 · 查詢無記錄 / 超時由調試器展示固定異常出口': 'A saída normal é editável · Os cenários sem registos e de tempo limite utilizam saídas de exceção fixas.',
  '節點配置': 'Configuração do nó',
  '節點名稱': 'Nome do nó',
  '節點類型': 'Tipo de nó',
  '下一節點 / 連線': 'Nó seguinte / ligação',
  '下一節點': 'Nó seguinte',
  '請選擇出口': 'Selecione uma saída',
  '操作即時保存到本頁籤工作區草稿。畫布不執行真實查詢或報修。': 'As alterações são guardadas imediatamente no rascunho deste separador. O diagrama não executa consultas nem regista avarias reais.',
  '流程調試': 'Teste do fluxo',
  '調試場景': 'Cenário de teste',
  '正常服務': 'Serviço normal',
  '無匹配記錄': 'Sem registos correspondentes',
  '查詢超時': 'Tempo limite da consulta',
  '開始試運行': 'Iniciar teste',
  '下一步': 'Passo seguinte',
  '運行至結束': 'Executar até ao fim',
  '運行記錄': 'Registo da execução',
  '超時轉人工': 'Tempo limite: encaminhar para operador',
  '無記錄澄清': 'Sem registos: pedir esclarecimentos',
  '調試步驟 · 不計入真實服務耗時': 'Passo de teste · Não incluído no tempo do serviço real',
  '尚未運行。': 'Ainda não executado.',
  '流程變量': 'Variáveis do fluxo',
  '變量': 'Variável',
  '來源': 'Origem',
  '展示規則': 'Regra de apresentação',
  '客戶身份': 'Identidade do cliente',
  '身份確認節點': 'Nó de confirmação da identidade',
  '僅使用測試賬戶': 'Utiliza apenas a conta de teste',
  '查詢結果': 'Resultado da consulta',
  '正常 / 無記錄 / 超時': 'Normal / sem registos / tempo limite',
  '回答依據': 'Base da resposta',
  '工作區模板或知識': 'Modelo ou conhecimento da área de trabalho',
  '後臺可見，電話不念編號': 'Visível na consola; os números não são lidos ao telefone',
  '開始': 'Início',
  '確認': 'Confirmação',
  '業務查詢': 'Consulta do serviço',
  '知識檢索': 'Pesquisa de conhecimento',
  '回答': 'Resposta',
  '結束': 'Fim',
  '缺少開始節點': 'Falta o nó inicial',
  '流程包含循環': 'O fluxo contém um ciclo',
  '存在不可達節點': 'Existem nós inacessíveis',
  '電費賬單查詢': 'Consulta de fatura de eletricidade',
  '身份確認 · 賬單查詢 · B 類業務模板': 'Confirmação de identidade · Consulta de fatura · Modelo de serviço da classe B',
  '身份確認': 'Confirmação da identidade',
  '查詢本期賬單': 'Consultar fatura atual',
  'B 類賬單模板': 'Modelo de fatura da classe B',
  '服務結束': 'Fim do serviço',
  '停電諮詢與報修': 'Informações e comunicação de interrupções',
  '地址採集 · 停電查詢 · 報修確認': 'Recolha do endereço · Consulta da interrupção · Confirmação do pedido',
  '確認澳門地址': 'Confirmar endereço de Macau',
  '查詢停電信息': 'Consultar interrupção de energia',
  '確認報修意願': 'Confirmar pedido de assistência',
  '報修登記確認': 'Confirmar registo do pedido',
  '常見問題知識問答': 'Perguntas frequentes',
  '意圖判斷 · 知識檢索 · C 類有據回答': 'Deteção da intenção · Pesquisa de conhecimento · Resposta fundamentada da classe C',
  '識別諮詢意圖': 'Identificar intenção',
  '判斷': 'Decisão',
  '檢索已審核知識': 'Pesquisar conhecimento aprovado',
  'C 類知識回答': 'Resposta de conhecimento da classe C',
  '確認解決並結束': 'Confirmar resolução e terminar',
  '待處理': 'Pendente',
  '解析預覽': 'Pré-visualização',
  '知識切片': 'Segmentação',
  '檢索驗證': 'Validação da pesquisa',
  '審核確認': 'Confirmação da revisão',
  '完成審核': 'Concluir revisão',
  '知識加工': 'Tratamento de conhecimento',
  '回答策略 A / B / C': 'Estratégias de resposta A / B / C',
  '知識文檔加工區': 'Tratamento de documentos de conhecimento',
  '與真實知識庫隔離。文件在瀏覽器內處理，尚未上傳服務器。': 'Esta área está isolada da base de conhecimento real. Os ficheiros são tratados no navegador e ainda não foram enviados ao servidor.',
  '選擇文本文件': 'Selecionar ficheiro de texto',
  '加工區僅接受 256 KB 以內的 TXT / Markdown。': 'Esta área aceita apenas ficheiros TXT ou Markdown até 256 KB.',
  '文件讀取失敗，請重新選擇。': 'Não foi possível ler o ficheiro. Selecione-o novamente.',
  '原文 / 解析預覽': 'Texto original / pré-visualização',
  '文檔內容': 'Conteúdo do documento',
  '支持 TXT / Markdown，最大 256 KB。PDF、Word 與 OCR 解析暫未接入。': 'São suportados ficheiros TXT e Markdown até 256 KB. O tratamento de PDF, Word e OCR ainda não está disponível.',
  '切片預覽': 'Pré-visualização dos segmentos',
  '切片': 'Segmento',
  '工作區知識': 'Conhecimento da área de trabalho',
  '完成解析後生成切片。按空行分段，可手動編輯。': 'Os segmentos são gerados após a análise. A separação usa linhas vazias e pode ser editada manualmente.',
  '切片檢索驗證': 'Validação da pesquisa nos segmentos',
  '僅在當前切片中執行文本包含匹配，不調用向量模型。': 'Executa apenas uma correspondência textual nos segmentos atuais, sem chamar o modelo vetorial.',
  '檢索驗證問題': 'Pergunta para validação da pesquisa',
  '檢索切片': 'Pesquisar segmentos',
  '未命中：請調整問題或補充知識。': 'Sem resultados. Ajuste a pergunta ou acrescente conhecimento.',
  '我已核對切片與原文，確認完成工作區審核。': 'Comparei os segmentos com o texto original e confirmo a conclusão da revisão nesta área de trabalho.',
  '開始解析預覽': 'Analisar e pré-visualizar',
  '生成知識切片': 'Gerar segmentos',
  '確認檢索結果': 'Confirmar resultados',
  '提交審核': 'Submeter para revisão',
  '審核已完成': 'Revisão concluída',
  '任何步驟都不會改變真實 RAG 或知識導航內容。': 'Nenhum destes passos altera o RAG real nem a navegação de conhecimento.',
  '標準話術': 'Texto padrão',
  '業務模板': 'Modelo de serviço',
  '知識問答': 'Resposta de conhecimento',
  '用電安全提醒': 'Aviso de segurança elétrica',
  '固定原文輸出，不交由模型改寫。': 'Apresenta o texto original sem o enviar ao modelo para reformulação.',
  '賬單查詢': 'Consulta de fatura',
  '只填充業務字段；未認證、無記錄和超時分別處理。': 'Preenche apenas os campos do serviço; trata separadamente os casos sem autenticação, sem registos e com tempo limite.',
  '繳費方式諮詢': 'Informações sobre formas de pagamento',
  '僅根據已審核知識回答；證據不足時澄清或轉人工。電話播報不包含來源編號。': 'Responde apenas com conhecimento aprovado; quando a evidência é insuficiente, pede esclarecimentos ou encaminha para um operador. A leitura telefónica não inclui números de fontes.',
  '後臺保留證據，客戶側使用簡潔自然的回答。': 'A consola conserva a evidência e apresenta ao cliente uma resposta curta e natural.',
  '回答內容 / 策略': 'Conteúdo / estratégia da resposta',
  '保存回答草稿': 'Guardar rascunho da resposta',
  '電話播報文本預覽': 'Pré-visualização do texto telefónico',
  'C 類在“運行數據”中測試真實檢索；此處僅編輯回答約束，不生成模型回覆。': 'Teste a pesquisa real da classe C em “Dados de execução”. Aqui apenas se editam as regras da resposta; não é gerada uma resposta do modelo.',
  '測試賬單字段 · 非真實客戶信息': 'Campos de fatura de teste · Sem dados reais de clientes',
  '標準話術原文預覽 · 不經過模型改寫': 'Pré-visualização do texto padrão · Sem reformulação pelo modelo',
  '客戶回答不包含來源編號；後臺檢索證據仍然保留。': 'A resposta ao cliente não inclui números de fontes; a evidência da pesquisa permanece na consola.',
  '9 月 30 日': '30 de setembro',
  '服務記錄': 'Registos de atendimento',
  '歷史會話': 'Conversas anteriores',
  '全部狀態': 'Todos os estados',
  '全部策略': 'Todas as estratégias',
  '覆核完成': 'Revisão concluída',
  '已解決': 'Resolvido',
  '客戶進入': 'Entrada do cliente',
  '測試賬戶': 'Conta de teste',
  '識別與路由': 'Reconhecimento e encaminhamento',
  '流程處理': 'Execução do fluxo',
  '知識與業務依據': 'Conhecimento e dados do serviço',
  '回答與語音': 'Resposta e voz',
  '客戶側輸出不包含證據編號；發音詞典待接入語音服務。': 'A resposta ao cliente não inclui números de evidência; o dicionário de pronúncia ainda não está ligado ao serviço de voz.',
  '服務結果': 'Resultado do serviço',
  '會話數據來源': 'Origem dos dados da conversa',
  '按最近更新時間排序，保留原始對話記錄。': 'Ordenado pela atualização mais recente, preservando o registo original da conversa.',
  '按渠道、回答策略和處理狀態快速定位服務記錄。': 'Localize rapidamente os registos por canal, estratégia de resposta e estado.',
  '搜索服務會話': 'Pesquisar conversas de atendimento',
  '搜索會話標題或編號': 'Pesquisar título ou número da conversa',
  '搜索標題、問題或編號': 'Pesquisar título, pergunta ou número',
  '正在加載會話…': 'A carregar conversas…',
  '暫無符合條件的會話。': 'Não existem conversas correspondentes.',
  '處理中': 'Em processamento',
  '會話詳情': 'Detalhes da conversa',
  '條消息': 'mensagens',
  '讀取中…': 'A carregar…',
  '會話讀取失敗。': 'Não foi possível carregar a conversa.',
  '重試讀取': 'Tentar novamente',
  '選擇一條會話，查看客戶問題與客服回覆。': 'Selecione uma conversa para consultar as perguntas do cliente e as respostas do atendimento.',
  '刷新快照': 'Atualizar instantâneo',
  '加載更早記錄': 'Carregar registos anteriores',
  '當前窗口沒有客戶消息或客服回覆。': 'Não existem mensagens do cliente nem respostas do atendimento neste intervalo.',
  '歷史對話': 'Histórico da conversa',
  '記錄快照 · 渠道、語言和語音版本未採集。': 'Instantâneo do registo · O canal, o idioma e a versão de voz não foram recolhidos.',
  '會話渠道': 'Canal da conversa',
  '處理狀態': 'Estado do tratamento',
  '回答策略篩選': 'Filtrar estratégia de resposta',
  '共': 'Total:',
  '服務主題': 'Tema do serviço',
  '渠道 / 語言': 'Canal / idioma',
  '操作': 'Ação',
  '查看詳情': 'Ver detalhes',
  '沒有匹配的會話。': 'Nenhuma conversa corresponde aos filtros.',
  '清空篩選條件': 'Limpar filtros',
  '服務記錄分頁': 'Paginação dos registos de atendimento',
  '每頁 8 條': '8 por página',
  '第': 'Página',
  '頁': '',
  '上一頁': 'Anterior',
  '下一頁': 'Seguinte',
  '服務記錄詳情': 'Detalhes do registo de atendimento',
  '服務詳情': 'Detalhes do serviço',
  '查看關聯整改': 'Ver correção associada',
  '標註問題並建立整改': 'Assinalar problema e criar correção',
  '對話內容': 'Conteúdo da conversa',
  '客戶': 'Cliente',
  '客服': 'Atendimento',
  '處理依據': 'Base do tratamento',
  '查看流程編排': 'Ver configuração do fluxo',
  '全部用例': 'Todos os casos',
  '通過': 'Aprovado',
  '未通過': 'Reprovado',
  '質檢整改 · 可重複驗證': 'Correção da qualidade · Validação repetível',
  '氹仔地址讀音核對': 'Verificação da pronúncia do endereço da Taipa',
  '整改中': 'Em correção',
  '待標註': 'Por assinalar',
  '問題臺賬': 'Registo de problemas',
  '問題分類': 'Categoria do problema',
  '地址 / 粵語發音': 'Endereço / pronúncia em cantonês',
  '責任角色': 'Responsável',
  '知識與語音營運': 'Operações de conhecimento e voz',
  '驗收要求': 'Critérios de aceitação',
  '完整詞條使用 taam5 zai2；不替換其他詞中的單字。': 'Utilizar taam5 zai2 para o termo completo, sem substituir o mesmo caráter noutros termos.',
  '配置版本': 'Versão da configuração',
  '尚未完成審核': 'Revisão ainda não concluída',
  '建立整改任務': 'Criar tarefa de correção',
  '查看來源會話': 'Ver conversa de origem',
  '編輯關聯發音規則': 'Editar regra de pronúncia associada',
  '迴歸與覆核': 'Regressão e revisão',
  '基線結果': 'Resultado de referência',
  '當前草稿': 'Rascunho atual',
  '規則校驗 · 當前版本測試集；不包含模型評分和音頻質量檢測。': 'Validação de regras com o conjunto de testes da versão atual; não inclui avaliação do modelo nem qualidade do áudio.',
  '運行規則迴歸': 'Executar regressão das regras',
  '完成覆核': 'Concluir revisão',
  '整改覆核完成，等待發布。': 'A revisão da correção foi concluída e aguarda publicação.',
  '迴歸測試集': 'Conjunto de testes de regressão',
  '固定 20 條用例 · 修改詞典後必須重新運行當前版本': '20 casos fixos · Volte a executar a versão atual depois de alterar o dicionário',
  '評測結果篩選': 'Filtrar resultados da avaliação',
  '編號': 'Número',
  '檢查項': 'Item verificado',
  '基線': 'Referência',
  '當前結果': 'Resultado atual',
  '暫無符合條件的結果。': 'Não existem resultados correspondentes.',
  '氹仔完整地名播報': 'Leitura completa do topónimo Taipa',
  '氹仔地址上下文匹配': 'Correspondência do contexto do endereço da Taipa',
  '標準話術保持原文': 'Manter o texto padrão original',
  '賬單字段填充': 'Preencher campos da fatura',
  '知識依據保留': 'Preservar a evidência de conhecimento',
  '意圖：': 'Intenção:',
  '回答策略：': 'Estratégia de resposta:',
  '用例': 'Caso',
  '草稿': 'Rascunho',
  '質檢列表讀取失敗，請刷新重試。': 'Não foi possível carregar a lista de avaliações. Atualize e tente novamente.',
  '質檢列表讀取失敗。': 'Não foi possível carregar a lista de avaliações.',
  '深繹未來 · 服務營運': 'Deep Future · Operações do serviço',
  '會話質量中心': 'Centro de qualidade das conversas',
  '從真實對話定位問題，用原始執行記錄核驗每一項評分。': 'Identifique problemas em conversas reais e confirme cada pontuação com os registos de execução originais.',
  '刷新記錄': 'Atualizar registos',
  '已質檢會話': 'Conversas avaliadas',
  '待覆核任務': 'Avaliações por rever',
  '未關閉整改': 'Correções pendentes',
  '搜索歷史會話': 'Pesquisar conversas anteriores',
  '搜索標題、編號或質檢意圖': 'Pesquisar título, número ou intenção avaliada',
  '預設篩選': 'Filtrar predefinição',
  '全部預設': 'Todas as predefinições',
  '質檢狀態篩選': 'Filtrar estado da avaliação',
  '未質檢': 'Não avaliada',
  '評估中': 'Em avaliação',
  '失敗待重試': 'Falhou; tentar novamente',
  '已覆核': 'Revista',
  '高風險': 'Risco elevado',
  '質檢分數篩選': 'Filtrar pontuação',
  '全部分數': 'Todas as pontuações',
  '低於 60 分': 'Abaixo de 60 pontos',
  '低於 80 分': 'Abaixo de 80 pontos',
  '低於 90 分': 'Abaixo de 90 pontos',
  '會話 / 時間': 'Conversa / hora',
  '意圖與預設': 'Intenção e predefinição',
  '自動評分': 'Pontuação automática',
  '待分析': 'Por analisar',
  '未記錄預設': 'Predefinição não registada',
  '覆蓋': 'Cobertura',
  '人工': 'Humana',
  '會話進行中': 'Conversa em curso',
  '正在讀取完整會話與工具記錄…': 'A carregar a conversa completa e os registos das ferramentas…',
  '返回會話列表': 'Voltar à lista de conversas',
  '歷史快照只讀；查看與質檢不切換正在使用的客服會話。未採集的渠道、錄音和語音版本不推斷補齊。': 'Os instantâneos históricos são apenas de leitura. A consulta e a avaliação não alteram a conversa de atendimento ativa. Os canais, gravações e versões de voz não recolhidos não são preenchidos por estimativa.',
  '質檢記錄加載失敗。': 'Não foi possível carregar os registos de avaliação.',
  '質檢任務': 'Tarefas de avaliação',
  '待覆核與整改': 'Revisões e correções pendentes',
  '評分規則': 'Regras de pontuação',
  '質量營運 · 證據可追溯': 'Operações de qualidade · Evidência rastreável',
  '會話質檢工作台': 'Área de controlo de qualidade das conversas',
  '自動評分、人工覆核與整改記錄分別保留。歷史質檢不會修改原始對話。': 'A pontuação automática, a revisão humana e as correções são registadas separadamente. As avaliações históricas não alteram a conversa original.',
  '刷新質檢任務': 'Atualizar avaliações',
  '六維評分權重': 'Pesos das seis dimensões',
  '規則 quality-v2。調整只影響下一次檢查，每次任務保存完整權重，不會覆蓋歷史評分。': 'Regra quality-v2. Os ajustes afetam apenas a avaliação seguinte; cada tarefa conserva todos os pesos e não substitui pontuações anteriores.',
  '意圖理解與路徑': 'Compreensão da intenção e percurso',
  '檢索質量': 'Qualidade da pesquisa',
  '回答準確性與依據': 'Exatidão e fundamentação da resposta',
  '處理完整性': 'Integridade do tratamento',
  '服務表達與語言': 'Comunicação e idioma do serviço',
  '執行與響應效率': 'Eficiência da execução e resposta',
  '權重': 'Peso',
  '權重合計：': 'Total dos pesos:',
  '，必須為 100% 才能開始質檢。': '; é necessário totalizar 100% para iniciar a avaliação.',
  '不適用維度不計入總分。缺少應有證據時顯示覆蓋率並暫不生成總分。高風險問題獨立標記，不能用平均分抵消。': 'As dimensões não aplicáveis não entram na pontuação total. Quando falta evidência necessária, é apresentada a cobertura e a pontuação total fica pendente. Os riscos elevados são assinalados separadamente e não podem ser compensados pela média.',
  '執行效率使用事件計時規則；其他維度為模型建議，人工覆核後保留獨立記錄。未採集的語音指標不參與評分。': 'A eficiência usa os tempos dos eventos; as restantes dimensões são propostas pelo modelo e a revisão humana é registada em separado. Os indicadores de voz não recolhidos não entram na pontuação.',
  '正在加載質檢任務…': 'A carregar avaliações…',
  '會話 / 評估時間': 'Conversa / hora da avaliação',
  '覆核 / 整改': 'Revisão / correção',
  '證據覆蓋': 'Cobertura da evidência',
  '未建立整改': 'Sem correção criada',
  '已驗收': 'Validada',
  '查看評分與證據': 'Ver pontuação e evidência',
  '暫無質檢任務。': 'Não existem tarefas de avaliação.',
  '選擇會話開始質檢': 'Selecionar conversa para avaliar',
  '失敗': 'Falhou',
  '狀態讀取失敗，請點擊刷新質檢結果。': 'Não foi possível ler o estado. Atualize o resultado da avaliação.',
  '操作失敗，請重試。': 'A operação falhou. Tente novamente.',
  '會話詳情 · ': 'Detalhes da conversa ·',
  '輪': 'Turno',
  '個輪次': 'turnos',
  '快照截至事件': 'Instantâneo até ao evento',
  '自動質檢總分': 'Pontuação automática total',
  '質檢狀態': 'Estado da avaliação',
  '安全關注': 'Risco e segurança',
  '待檢查': 'Por verificar',
  '已人工確認': 'Confirmado por revisão humana',
  '高風險 · 必須覆核': 'Risco elevado · Revisão obrigatória',
  '查看分項結論': 'Ver resultados por dimensão',
  '待評估': 'Por avaliar',
  '評估模型': 'Modelo de avaliação',
  '完整會話檢查': 'Avaliação da conversa completa',
  '原會話已有更新，當前展示歷史質檢快照。': 'A conversa original foi atualizada; está a ser apresentado o instantâneo histórico da avaliação.',
  '查看或檢查輪次': 'Ver ou avaliar turno',
  '全部已結束輪次': 'Todos os turnos concluídos',
  '正在質檢…': 'A avaliar…',
  '重新質檢': 'Voltar a avaliar',
  '開始質檢': 'Iniciar avaliação',
  '刷新質檢結果': 'Atualizar resultado',
  '重新質檢會創建新記錄，不重跑原業務工具。': 'Uma nova avaliação cria um novo registo e não volta a executar as ferramentas do serviço.',
  '未結束輪次仍可查看，但自動質檢會跳過；也可以選擇任一已結束輪次單獨質檢。': 'Os turnos por concluir podem ser consultados, mas são ignorados pela avaliação automática. Também pode avaliar separadamente qualquer turno concluído.',
  '會話詳情視圖': 'Vistas dos detalhes da conversa',
  '對話與評分': 'Conversa e pontuação',
  '執行過程': 'Execução',
  '檢索依據': 'Evidência da pesquisa',
  '質檢與覆核記錄': 'Avaliações e revisões',
  '原始對話': 'Conversa original',
  '查看對應過程': 'Ver execução correspondente',
  '六維質量評分': 'Pontuação nas seis dimensões',
  '開始質檢後顯示逐輪評分、扣分原因及證據。': 'Depois de iniciar a avaliação, são apresentadas as pontuações por turno, as deduções e as evidências.',
  '意圖為質檢事後分析': 'A intenção é inferida apenas para a análise posterior',
  '分': 'pontos',
  '不適用': 'Não aplicável',
  '證據不足': 'Evidência insuficiente',
  '建議：': 'Sugestão:',
  '證據': 'Evidência',
  '語音專項：錄音、STT準確率、播報中斷和字幕對齊未採集，不參與評分。': 'Voz: gravações, exatidão do STT, interrupções da reprodução e alinhamento das legendas não foram recolhidos e não entram na pontuação.',
  '執行軌跡': 'Registo da execução',
  '歷史事件 · 只讀': 'Eventos históricos · Apenas leitura',
  '已定位證據': 'Evidência localizada',
  '耗時': 'Duração',
  '首 token': 'Primeiro token',
  '當時的檢索依據': 'Evidência da pesquisa nesse momento',
  '展示記錄中的知識檢索工具輸入和返回。排序分數不等於準確率；沒有人工標註時不計算 Precision / Recall。': 'Apresenta os pedidos e resultados das ferramentas de pesquisa registados. A pontuação de ordenação não representa exatidão; sem anotação humana, não são calculados Precision nem Recall.',
  '定位軌跡': 'Localizar no registo',
  '查詢參數': 'Parâmetros da consulta',
  '已記錄返回': 'Resultado registado',
  '未記錄返回結果': 'Resultado não registado',
  '當前範圍沒有知識檢索工具記錄，無法展示歷史命中片段。': 'Não existem registos de ferramentas de pesquisa neste âmbito, pelo que não é possível apresentar os trechos recuperados.',
  '人工覆核與整改': 'Revisão humana e correções',
  '保留自動結果。覆核和整改動作均需填寫依據；此處為本機操作記錄，不代表已接入人員身份認證。': 'Os resultados automáticos são preservados. As revisões e correções exigem uma justificação; estes são registos locais e não representam autenticação de operadores.',
  '覆核或驗收依據': 'Justificação da revisão ou validação',
  '人工總分（留空保留自動結果）': 'Pontuação humana total (deixe em branco para manter o resultado automático)',
  '人工總分': 'Pontuação humana total',
  '確認並保存人工評分': 'Confirmar e guardar pontuação humana',
  '建立整改': 'Criar correção',
  '重新打開整改': 'Reabrir correção',
  '完成整改驗收': 'Concluir validação da correção',
  '人工覆核': 'Revisão humana',
  '整改驗收': 'Validação da correção',
  '重新打開': 'Reabrir',
  '人工分數': 'Pontuação humana',
  '歷史質檢版本': 'Versões anteriores da avaliação',
  '查看該次結果': 'Ver este resultado',
  '本次權重與範圍': 'Pesos e âmbito desta avaliação',
  '澳門地址縮寫展開': 'Expansão das abreviaturas de endereços de Macau',
  '樓棟號連續數讀法': 'Leitura de números de edifícios',
  '樓層範圍與組合': 'Intervalos e combinações de pisos',
  '銀行縮寫按語言展開': 'Expansão de abreviaturas bancárias por idioma',
  '月日日期讀法': 'Leitura de datas com mês e dia',
  '澳門元金額讀法': 'Leitura de valores em patacas',
  '百分比讀法': 'Leitura de percentagens',
  '正則模式': 'Expressão regular',
  '縮寫表': 'Tabela de abreviaturas',
  '按地址語義展開': 'Expandir conforme o significado do endereço',
  '數值讀法 + 棟': 'Leitura do número + edifício',
  '地下至三樓、地下加一樓加二樓': 'Rés-do-chão ao 3.º andar; rés-do-chão mais 1.º e 2.º andares',
  '選定語言的機構全稱': 'Nome completo da entidade no idioma selecionado',
  '月份和日期轉換為中文數值': 'Converter mês e dia para a leitura chinesa',
  '澳門元 + 數值讀法': 'Patacas + leitura do valor',
  '百分之 + 數值讀法': 'Percentagem + leitura do valor',
  '工作區已重置，運行配置未改變。': 'A área de trabalho foi reposta; a configuração em execução não foi alterada.',
  '發音規則已啟用，等待試讀與發佈審核。': 'A regra de pronúncia foi ativada e aguarda teste e revisão para publicação.',
  '發音規則已停用，等待試讀與發佈審核。': 'A regra de pronúncia foi desativada e aguarda teste e revisão para publicação.',
  '已建立整改任務：氹仔地址讀音核對。': 'Foi criada uma tarefa de correção para verificar a pronúncia do endereço da Taipa.',
  '請填寫讀音規則。': 'Preencha a regra de pronúncia.',
  '讀音規則沒有變化。': 'A regra de pronúncia não foi alterada.',
  '發音規則已保存，等待迴歸與覆核。': 'A regra de pronúncia foi guardada e aguarda regressão e revisão.',
  '規則迴歸完成：20 / 20 通過。等待覆核。': 'Regressão concluída: 20 de 20 casos aprovados. Aguarda revisão.',
  '規則迴歸完成：18 / 20 通過。請核對氹仔讀音。': 'Regressão concluída: 18 de 20 casos aprovados. Verifique a pronúncia de Taipa.',
  '規則草稿': 'Rascunho da regra',
  '詞條草稿': 'Rascunho do termo',
  '請先建立整改任務，並通過當前版本的規則迴歸。': 'Crie primeiro a tarefa de correção e conclua a regressão da versão atual.',
  '覆核已完成，等待發布至電話服務。': 'A revisão foi concluída e aguarda publicação no serviço telefónico.',
  '歡迎語不能為空。': 'A saudação não pode ficar vazia.',
  '渠道草稿已保存，線路尚未接入。': 'O rascunho do canal foi guardado; a linha ainda não está ligada.',
  '回答內容不能為空。': 'A resposta não pode ficar vazia.',
  '業務模板必須保留 {{amount}} 和 {{date}}。': 'O modelo de serviço deve manter {{amount}} e {{date}}.',
  '回答草稿已保存，尚未發佈至客服。': 'O rascunho da resposta foi guardado e ainda não foi publicado no atendimento.',
  '檢索驗證通過，可以提交審核。': 'A validação da pesquisa foi aprovada e pode ser submetida para revisão.',
  '未命中有效切片，請調整檢索內容。': 'Não foi encontrado um segmento válido. Ajuste o conteúdo da pesquisa.',
  '文檔內容不能為空。': 'O documento não pode ficar vazio.',
  '請先完成切片檢索驗證。': 'Conclua primeiro a validação da pesquisa nos segmentos.',
  '請先核對原文並確認審核。': 'Compare primeiro o texto original e confirme a revisão.',
  '切片內容不能為空。': 'Os segmentos não podem ficar vazios.',
  '文檔審核已完成，尚未發佈至運行知識庫。': 'A revisão do documento foi concluída; ainda não foi publicado na base de conhecimento em execução.',
  '處理步驟已完成。': 'Passo concluído.',
}

/**
 * Translate rehearsal copy only while Portuguese is active. Historical
 * customer messages and knowledge excerpts are passed through unchanged.
 * @param t - namespace translator used to identify the active locale.
 * @param source - existing Chinese operator-interface copy.
 * @returns Portuguese copy when available, otherwise the source text.
 */
export function operationsText(t: LocaleProbe, source: string): string {
  if (t('localeCode') !== 'pt') return source
  const direct = PORTUGUESE_TEXT[source]
  if (direct !== undefined) return direct
  const missingName = /^(.+) 缺少名稱$/u.exec(source)
  if (missingName) return `${missingName[1]} não tem nome`
  const missingExit = /^(.+) 缺少有效出口$/u.exec(source)
  if (missingExit) return `${missingExit[1]} não tem uma saída válida`
  return source
}
